apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=              # base64 of 'postgres'
  POSTGRES_PASSWORD: U3VwZXJTZWNyZXQxMjM=  # base64 of 'SuperSecret123'